room/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('room_detail/<str:pk>',views.room_detail,name="room_detail"),
    path('addroom/',views.addroom,name="addroom"),
    path('update-room/<str:pk>',views.update_room,name="update-room"),
    path('delete-room/<str:pk>',views.delete_room,name="delete-room"),
    path('user-profile/<str:pk>',views.user_profile,name="user-profile"),
    path('delete-message/<str:pk>',views.delete_message,name="delete-message"),
    path('current_user_profile/',views.current_user_profile,name="current_user_profile"),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('room/',include('room.urls')),
]

room/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL , null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL , null=True) 
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=500,null=True, blank=True)
    participants = models.ManyToManyField(User , related_name="participants", blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room , on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated' , '-created']

    def __str__(self):
        return self.body[0:50]

pages/templates/pages/activity_component.html
<div class="activities">
  <div class="activities__header">
      <h2>Recent Activities</h2>
  </div>
  {% for message in room_message %}
  <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
          <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                  <img src="{{message.user.profile.profile_picture.url}}" />
              </div>
              <p>
                  @{{message.user.username}}
                  <span>{{message.created|timesince}} ago</span>
              </p>
          </a>

          {% if request.user == message.user %}
          <div class="roomListRoom__actions">
              <a href="{% url 'delete-message' message.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                          d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                      </path>
                  </svg>
              </a>
          </div>
          {% endif %}

      </div>
      <div class="activities__boxContent">
          <p>replied to post “<a href="{% url 'room_detail' message.room.id %}">{{message.room}}</a>”</p>
          <div class="activities__boxRoomContent">{{message.body}}</div>
      </div>
  </div>
  {% endfor %}

</div>

pages/templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}"/>
    <title>
      {% block title %}
        StudyBuddy - Find study partners around the world!
      {% endblock title %}
    </title>
  </head>

  <body>

  {% include 'pages/navbar.html' %}

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

{% block content %}

{% endblock content %}

  </body>
    <script src="{% static 'js/script.js' %}"></script>
</html>

pages/templates/pages/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{room.host.profile.profile_picture.url}}" />
            </div>
            <span>@{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'room_detail' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'room_detail' room.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{room.participants.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
</div>
{% endfor %}

pages/templates/pages/index.html
{% extends 'pages/base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}

<main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
        {% include 'pages/topic_component.html' %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{Room_count}} Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'addroom' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
          {% comment %} {% for i in Room_data %}
          <div class="roomListRoom">
            <div class="roomListRoom__header">
              <a href="{% url 'user-profile' i.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="{{i.host.profile.profile_picture.url}}" />
                </div>
                <span>@{{i.host}}</span>
              </a>
              <div class="roomListRoom__actions">
                <span>5 days ago</span>
              </div>
            </div>
            <div class="roomListRoom__content">
              <a href="{% url 'room_detail' i.id %}">{{i.name}}</a>
              <p>
                {{i.description}}
              </p>
            </div>
            <div class="roomListRoom__meta">
              <a href="room.html" class="roomListRoom__joined">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>user-group</title>
                  <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
                  ></path>
                  <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
                  ></path>
                  <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
                  ></path>
                  <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
                  ></path>
                </svg>
                5.3k Joined
              </a>
              <p class="roomListRoom__topic">{{i.topic}}</p>
            </div>
          </div>
          {% endfor %} {% endcomment %}
          {% include 'pages/feed_component.html' %}
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        {% include 'pages/activity_component.html' %}
        <!-- Activities End -->
      </div>
    </main>

{% endblock content %}

pages/templates/pages/login.html
{% extends 'pages/base.html' %}
{% load static %}

{% block title %} Login {% endblock title %} 

{% block content %}
<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="#" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="room_name">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              placeholder="e.g. dennis_ivy"
            />
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'signup' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

pages/templates/pages/navbar.html
{% load static %}
<header class="header header--loggedIn">
  <div class="container">
    <a href="/" class="header__logo">
      <img src="{% static 'images/logo.svg' %}" />
      <h1>StudyBuddy</h1>
    </a>
    <form method="GET" class="header__search" action="">
      <label>
        <svg
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          width="32"
          height="32"
          viewBox="0 0 32 32"
        >
          <title>search</title>
          <path
            d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
          ></path>
        </svg>
        <input placeholder="Search for rooms..." name="q"/>
      </label>
    </form>
    <nav class="header__menu">
      <!-- Not Logged In -->
      
       

      <!-- Logged In -->
      {% if request.user.is_authenticated %}
      <div class="header__user">
        <a href="{% url 'current_user_profile' %}">
          <div class="avatar avatar--medium active">
            <img src="{{request.user.profile.profile_picture.url}}" />
          </div>
          <p>{{request.user.username}} <span>@{{request.user.username}}</span></p>
        </a>
        <button class="dropdown-button">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path> 
          </svg>
        </button>
      </div>
      {% else %}
      <a href="{% url 'login' %}">
        <img src="{% static 'images/avatar.svg' %}" />
        <p>Login</p>
      </a>
      {% endif %}
      

      <div class="dropdown-menu">
        <a href="{% url 'setting' %}" class="dropdown-link"
          ><svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>tools</title>
            <path
              d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
            ></path>
          </svg>
          Settings</a
        >
        <a href="{% url 'login' %}" class="dropdown-link"
          ><svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>sign-out</title>
            <path
              d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
            ></path>
            <path
              d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
            ></path>
          </svg>
          Logout</a
        >
      </div>
    </nav>
  </div>
</header>

pages/templates/pages/setting.html
{% extends 'pages/base.html' %} 
{% load static %}
{% block title %} Setting {% endblock title %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'index' %}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Settings</h3>
        </div>
      </div>

      <div class="settings layout__body">
        <div class="settings__avatar">
          <div class="avatar avatar--large active">
            <img src="  {% static 'images/avatar.svg' %}" id="preview-avatar" />
          </div>
        </div>
        <form class="form" action="#" method="POST">
          {% csrf_token %}
          <div class="form__group form__avatar">
            <label for="avatar">Upload Avatar</label>
            <input
              class="form__hide"
              type="file"
              name="profile_picture"
              id="avatar"
              value = "{{user_data.profile.profile_picture.url}}"
              accept="image/png, image/gif, image/jpeg"
            />
          </div>
          <div class="form__group">
            <label for="name">First Name</label>
            <input
              id="first_name"
              name="first_name"
              type="text"
              value="{{user_data.first_name}}"
              placeholder="e.g. Dennis Ivy"
            />
          </div>
          <div class="form__group">
            <label for="name">Last Name</label>
            <input
              id="lsat_name"
              name="last_name"
              type="text"
              value="{{user_data.last_name}}"
              placeholder="e.g. Dennis Ivy"
            />
          </div>
          <div class="form__group">
            <label for="username">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              value = "{{user_data.username}}"
              placeholder="e.g. @dennis_ivy"
            />
          </div>
          <div class="form__group">
            <label for="email">Email</label>
            <input
              id="email"
              name="email"
              type="email"
              value = "{{user_data.email}}"
              placeholder="e.g. user@domain.com"
            />
          </div>
          <div class="form__action">
            <a class="btn btn--dark" href="{% url 'profile' %}">Cancel</a>
            <button class="btn btn--main" type="submit">Update Settings</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

pages/templates/pages/signup.html
{% extends 'pages/base.html' %} 
{% load static %}

{% block title %} Signup {% endblock title %} 

{% block content %}
<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Sign up</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="#" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="fullname">First Name</label>
            <input
              id="fullname"
              name="first_name"
              type="text"
              placeholder="e.g. John"
            />
          </div>
          <div class="form__group form__group">
            <label for="fullname">Last Name</label>
            <input
              id="fullname"
              name="last_name"
              type="text"
              placeholder="e.g. Doe"
            />
          </div>
          <div class="form__group form__group">
            <label for="fullname">Email</label>
            <input
              id="email"
              name="email"
              type="email"
              placeholder="e.g. xyz@gmail.com"
            />
          </div>
          <div class="form__group form__group">
            <label for="room_name">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              placeholder="e.g. john_doe"
            />
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <div class="form__group">
            <label for="confirm_password">Confirm Password</label>
            <input
              id="confirm_password"
              name="confirm_password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Sign Up
          </button>
        </form>

        <div class="auth__action">
          <p>Already have an account?</p>
          <a href="{% url 'login' %}" class="btn btn--link">Log In</a>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

pages/templates/pages/topic_component.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="/" class="active">All <span>{{Topic_list.count}}</span></a>
      </li>
      <form>
    {% for topic in Topic_list %}
      <li>
        <a href="{% url 'index' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
      </li>
    {% endfor %}
    </form>
    </ul>
    <a class="btn btn--link" href="topics.html">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>